### ISSUE TITLE
Not working with Hugo 0.72.0

### ISSUE THREAD

**Issue by bishopnator** [okkur/syna-start#33] opened 2020-06-01 11:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
After git clone and hugo server -D it fails to build the site

**What you expected to happen**:
The site is built

**How to reproduce it (as minimally and precisely as possible)**:
* clone syna-start repository
* cd syna-start
* hugo server -D

**Anything else we need to know?**:
Output:
```
Building sites … WARN 2020/06/01 13:52:06 .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
ERROR 2020/06/01 13:52:06 render of "page" failed: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\_default\baseof.html:10:9": execute of template failed: template: _default/single.html:10:7: executing "_default/single.html" at <partial "helpers/fragments-renderer.html" (dict "page_scratch" .Scratch)>: error calling partial: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\partials\helpers\fragments-renderer.html:10:9": execute of template failed: template: partials/helpers/fragments-renderer.html:10:9: executing "partials/helpers/fragments-renderer.html" at <(not (isset .Params "slot")) (ne .Params.slot "")>: can't give argument to non-function not (isset .Params "slot")
ERROR 2020/06/01 13:52:06 render of "home" failed: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\_default\baseof.html:10:9": execute of template failed: template: _default/list.html:10:7: executing "_default/list.html" at <partial "helpers/fragments-renderer.html" (dict "page_scratch" .Scratch)>: error calling partial: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\partials\helpers\fragments-renderer.html:10:9": execute of template failed: template: partials/helpers/fragments-renderer.html:10:9: executing "partials/helpers/fragments-renderer.html" at <(not (isset .Params "slot")) (ne .Params.slot "")>: can't give argument to non-function not (isset .Params "slot")
Built in 362 ms
Error: Error building site: failed to render pages: render of "page" failed: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\_default\baseof.html:10:9": execute of template failed: template: _default/single.html:10:7: executing "_default/single.html" at <partial "helpers/fragments-renderer.html" (dict "page_scratch" .Scratch)>: error calling partial: "d:\Programming\GoHugo\syna-start\themes\syna\layouts\partials\helpers\fragments-renderer.html:10:9": execute of template failed: template: partials/helpers/fragments-renderer.html:10:9: executing "partials/helpers/fragments-renderer.html" at <(not (isset .Params "slot")) (ne .Params.slot "")>: can't give argument to non-function not (isset .Params "slot")
```

**Environment**:
- Syna Theme Starter version:  master (downloaded 01.06.2020)
- Hugo version:  Hugo Static Site Generator v0.72.0/extended windows/amd64 BuildDate: unknown
- Others:

**Comment by mpourismaiel** [comment] 2020-06-01 12:30
Thanks for reporting. Looking into it right away. Please use v0.71 for now until we find and resolve the issue. Also we'd be happy to receive a PR if you have a solution in mind.

**Comment by mpourismaiel** [comment] 2020-06-01 13:10
The problem is fixed within Syna. You can update the syna submodule within syna-start to fix the problem. We'll update the submodule on the repository as well.

Again, thanks for reporting the issue.

**Comment by stp-ip** [comment] 2020-06-01 14:52
Patch release is planned for tomorrow including updating the submodule to the latest patch.

**Comment by stp-ip** [comment] 2020-06-06 18:15
Sorry seems like I miscommunicated with the team. I'll get on the patch release myself first thing Monday.

**Closed** 2020-06-07 10:50 UTC
